[platformio]
default_envs = adafruit_qt_py_m0

[env:adafruit_qt_py_m0]
platform = atmelsam
board = adafruit_qt_py_m0
framework = arduino
monitor_speed = 115200
check_tool = cppcheck
check_skip_packages = yes
check_flags =
    cppcheck: --enable=warning,style,performance,portability
    cppcheck: --std=c++11
    cppcheck: --inline-suppr
    cppcheck: --suppress=missingIncludeSystem
    cppcheck: --suppress=noExplicitConstructor
check_src_filters =
    +<src/>
    +<include/>
    +<lib/>
build_flags =
    -DUSE_TINYUSB
lib_deps =
    adafruit/Adafruit NeoPixel @ ^1.15.5
    adafruit/RTClib @ ^2.1.4

[env:validation]
extends = env:adafruit_qt_py_m0
build_flags =
    ${env:adafruit_qt_py_m0.build_flags}
    -DNOVA_VALIDATION_MODE

[env:set_rtc]
extends = env:adafruit_qt_py_m0
build_flags =
    ${env:adafruit_qt_py_m0.build_flags}
    -DNOVA_SET_RTC_TO_BUILD_TIME
extra_scripts =
    pre:scripts/set_rtc_build_time.py

[env:native]
platform = native
test_framework = unity
test_filter =
    test_pulse
    test_animation_logic
    test_animation_state
