[platformio]
default_envs = adafruit_qt_py_m0

[env:adafruit_qt_py_m0]
platform = atmelsam
board = adafruit_qt_py_m0
framework = arduino
monitor_speed = 115200
build_flags =
    -DUSE_TINYUSB
lib_deps =
    adafruit/Adafruit NeoPixel @ ^1.15.5
    adafruit/RTClib @ ^2.1.4

[env:validation]
extends = env:adafruit_qt_py_m0
build_flags =
    ${env:adafruit_qt_py_m0.build_flags}
    -DNOVA_VALIDATION_MODE

[env:native]
platform = native
test_framework = unity
test_filter =
    test_pulse
    test_animation_logic
